#!/usr/bin/env ruby

# Play a raw audio content 
#
# you can create a compatible raw file with sox :
# sox /path/to/audio.file -t raw -c 2 -r 44100 -e signed-integer -b 16 audiocontent.raw 
#
# script/play < audiocontent.raw

require 'rubygems' unless ENV['NO_RUBYGEMS']
require "#{File.dirname(__FILE__)}/../lib/alsa"

include ALSA::PCM
ALSA.logger.level = Logger::DEBUG

unless ARGV.shift == "async"
  Playback.open do |playback|
    playback.write do |length|
      $stdin.read(length)
    end
  end
else
  Playback.open.write_in_background do |length|
    $stdin.read(length)
  end
  loop { sleep 10 }
end
